name: simple_result
description: Uma implementação leve e type-safe do padrão Result para Dart. Perfeita para Clean Architecture e aplicações Flutter, com suporte a sealed classes e pattern matching do Dart 3.
version: 1.0.1
repository: https://github.com/saulogatti/simple_result

environment:
  sdk: ^3.10.4

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
