name: simple_result
description: Uma implementação leve e type-safe do padrão Result para Dart. Perfeita para Clean Architecture e aplicações Flutter, com suporte a sealed classes e pattern matching do Dart 3.
version: 1.0.4
repository: https://github.com/saulogatti/simple_result

environment:
  sdk: ^3.11.0

# Add regular dependencies here.
dependencies:
  collection: 1.19.1
  bloc: ^9.2.0
  meta: ^1.17.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  get_it: ^9.2.1
dev_dependencies:
  lints: ^6.1.0
  test: ^1.29.0
